context:
  name: volta
  version: "2.0.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/volta-cli/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 0e93d17c36fb79222b10881d6c67d667483f85b19a0498eacfc535ef31894dbe

build:
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - cargo install --no-track --locked --root ${{ PREFIX }} --path .
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
    - volta --version

about:
  homepage: https://volta.sh
  summary: 'The Hassle-Free JavaScript Tool Manager'
  description: |
    Fast: Install and run any JS tool quickly and seamlessly! Volta is built in Rust and ships as a snappy static binary.
    Reliable: Ensure everyone in your project has the same tools—without interfering with their workflow.
    Universal: No matter the package manager, Node runtime, or OS, one command is all you need: `volta install`.
  license: BSD-2-Clause
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  repository: https://github.com/volta-cli/volta
  documentation: https://docs.volta.sh/guide

extra:
  recipe-maintainers:
    - eunos-1128
